[package]
name = "custom_error"
version = "0.1.0"
authors = ["anton_misa <anton_misa@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
